server:
 port: 9093

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka

spring:
 application:
  name: FOODCATALOGUE
 datasource: 
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/foodcataloguedb
  username: root
  password: MySql@123
  driver-class-name: com.mysql.cj.jdbc.Driver
  
 jpa:
  hibernate:
   generate-ddl: true
   ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL8Dialect
