server:
 port: 9091

eureka:
 client:
  service-url:
   defaultzone: http://localhost:8761/eureka

spring:
 application: 
  name: RESTAURANTLISTING
 datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/restuarantdb
  password: MySql@123
  username: root
  #ddl-auto: update
  #how-sql: true
  driver-class-name: com.mysql.cj.jdbc.Driver

 jpa:
  hibernate:
  generate-ddl: true 
  ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect
  
